//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all fields from in into out.
func (in *DatabaseMigration) DeepCopyInto(out *DatabaseMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *DatabaseMigration) DeepCopy() *DatabaseMigration {
	if in == nil {
		return nil
	}
	out := new(DatabaseMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *DatabaseMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields from in into out.
func (in *DatabaseMigrationList) DeepCopyInto(out *DatabaseMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *DatabaseMigrationList) DeepCopy() *DatabaseMigrationList {
	if in == nil {
		return nil
	}
	out := new(DatabaseMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *DatabaseMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields from in into out.
func (in *DatabaseMigrationSpec) DeepCopyInto(out *DatabaseMigrationSpec) {
	*out = *in
	out.Source = in.Source
	out.Source.SecretRef = in.Source.SecretRef
	out.Destination = in.Destination
	out.Destination.SecretRef = in.Destination.SecretRef
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(MigrationOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *DatabaseMigrationSpec) DeepCopy() *DatabaseMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields from in into out.
func (in *DatabaseMigrationStatus) DeepCopyInto(out *DatabaseMigrationStatus) {
	*out = *in
	if in.LastMigrationTime != nil {
		in, out := &in.LastMigrationTime, &out.LastMigrationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *DatabaseMigrationStatus) DeepCopy() *DatabaseMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields from in into out.
func (in *DatabaseRef) DeepCopyInto(out *DatabaseRef) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy returns a deep copy of the receiver.
func (in *DatabaseRef) DeepCopy() *DatabaseRef {
	if in == nil {
		return nil
	}
	out := new(DatabaseRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields from in into out.
func (in *LocalSecretRef) DeepCopyInto(out *LocalSecretRef) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *LocalSecretRef) DeepCopy() *LocalSecretRef {
	if in == nil {
		return nil
	}
	out := new(LocalSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields from in into out.
func (in *MigrationOptions) DeepCopyInto(out *MigrationOptions) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *MigrationOptions) DeepCopy() *MigrationOptions {
	if in == nil {
		return nil
	}
	out := new(MigrationOptions)
	in.DeepCopyInto(out)
	return out
}
